spring.application.name=RealTimeEventStreaming

spring.mongodb.uri=mongodb://localhost:27017/gaming_events

spring.kafka.bootstrap-servers=localhost:9092


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=gaming-event-consumers

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.RealTimeEventStreaming.domain

spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.jackson.serialization.write-dates-as-timestamps=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

management.endpoints.web.exposure.include=health,info